### ISSUE TITLE
"Núcleo EF" should be "EF Core"

### ISSUE THREAD

**Issue by divega** [aspnet/Docs.es-es#9]
EF Core is the name of the product, however in pages such as https://docs.microsoft.com/es-es/ef/core/modeling/owned-entities it is translated like "Núcleo EF". I assume "EF Core" and "Entity Framework Core" need to be added to a dictionary of terms that should not be translated.

I also assume that this affects other translations besides Spanish.

**Comment by CeciAc** [comment]
Hello, @divega 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @divega,
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/es-es/ef/core/modeling/owned-entities. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by divega** [comment]
@CeciAc de nada! :smile:. The have just noticed that on the article at https://docs.microsoft.com/es-es/ef/core/modeling/owned-entities#explicit-configuration, there is still a mix of references to EF Core and núcleo. Any idea why?

**Comment by CeciAc** [comment]
Hi @divega 
You won't be seeing the fixes until the next publishing round is live, but the suggestion was accepted and applied :) 

Kind regards,
Microsoft DOCS International Team
